
all:
	mkisofs -R                              \
                -b boot/grub/stage2_eltorito    \
                -no-emul-boot                   \
                -boot-load-size 4               \
                -A os                           \
                -input-charset utf8             \
                -quiet                          \
                -boot-info-table                \
                -o os.iso                       \
                iso

	cp os.iso ../../src/
clean:
	rm -rf os.iso
	rm -rf ../../src/os.iso
	